goku:
  build: .
  ports:
    - "3000:80"
    - "2222:22"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - .:/go/src/github.com/adamveld12/goku
  links:
    - consul

consul:
  image: smebberson/alpine-consul
